image:
  registry: "10.0.0.11:5000"
  backendRepo: "myapp-backend"
  frontendRepo: "myapp-frontend"
  tag: "prod-1.0.0"   # ❗ NO latest in PROD

ingress:
  enabled: true
  className: traefik

  hostApp: prod-app.arcadix.ai
  hostApi: prod-api.arcadix.ai

  tls:
    enabled: true
    issuer: letsencrypt-prod
    secretName: myapp-prod-tls

env:
  DB_HOST: postgres-postgresql.database.svc.cluster.local
  DB_PORT: "5432"
  DB_NAME: appdb
  DB_USER: appuser
