image:
  registry: "10.0.0.11:5000"
  backendRepo: "myapp-backend"
  frontendRepo: "myapp-frontend"
  tag: "latest"

ingress:
  enabled: true
  className: "traefik"
  hostApp: "dev-app.arcadix.ai"
  hostApi: "dev-api.arcadix.ai"

secrets:
  dbName: "appdb"
  dbUser: "appuser"
  dbPassword: "apppass"

env:
  DB_HOST: postgres-postgresql.database.svc.cluster.local
  DB_PORT: "5432"
  DB_NAME: appdb
  DB_USER: appuser
  DB_PASSWORD: apppass
